version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-analyzer
    volumes:
      - ../Task_project:/target_project
    command: >
      python main.py --project /target_project
      --target-function "service/task.py::TaskService.create_task"
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      PIP_DISABLE_PIP_VERSION_CHECK: 1